
server:
  port: 8095

logging:
  level:
    root: info
    com.tss: info

spring:
  application:
    name: tss-auth-server
  datasource:
    url: jdbc:mysql://dev.tss.com:3306/njit_oauth?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: njittss
    password: njittss!@#$5678

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

ribbon:
  eager-load:
    enabled: true
    clients: tss-auth-server
  ReadTimeout: 10000
  ConnectTimeout: 10000


security:
  oauth2:
    resource:
      filter-order: 3

# custom config
authentication: 
  oauth: 
    clientId: app
    clientSecret: app_20181206
    tokenValidityInSeconds: 1800
    scope: 
      - web
    grantType: 
      - password
      - refresh_token
